-- klarwert - migration 007: extended aliases per round 2
-- kein eigenes begin/commit hier: migrate.ts kapselt seit dem transaktions-disziplin-fix
-- (siehe applyMigrations) jede migration bereits selbst in einer echten transaktion; ein
-- zusätzliches begin hier kollidiert damit ("cannot start a transaction within a transaction").
insert or ignore into category_aliases (category_id, alias) select id, 'Nebenkosten' from categories where name = 'Wohnnebenkosten' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Betriebskosten' from categories where name = 'Wohnnebenkosten' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Hausgeld' from categories where name = 'Wohnnebenkosten' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Nebenkostenabrechnung' from categories where name = 'Wohnnebenkosten' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Müllgebühren' from categories where name = 'Wohnnebenkosten' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Wasser' from categories where name = 'Wohnnebenkosten' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Abwasser' from categories where name = 'Wohnnebenkosten' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Wohngeldabrechnung' from categories where name = 'Wohnnebenkosten' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Hausverwaltung' from categories where name = 'Wohnnebenkosten' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Baumarkt' from categories where name = 'Heimwerken und Garten' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Hornbach' from categories where name = 'Heimwerken und Garten' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Obi' from categories where name = 'Heimwerken und Garten' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Bauhaus' from categories where name = 'Heimwerken und Garten' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Toom' from categories where name = 'Heimwerken und Garten' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Werkzeug' from categories where name = 'Heimwerken und Garten' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Pflanzen' from categories where name = 'Heimwerken und Garten' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Gartencenter' from categories where name = 'Heimwerken und Garten' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Rasen' from categories where name = 'Heimwerken und Garten' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Garten' from categories where name = 'Heimwerken und Garten' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Heimwerker' from categories where name = 'Heimwerken und Garten' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Dünger' from categories where name = 'Heimwerken und Garten' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Erde' from categories where name = 'Heimwerken und Garten' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Energie' from categories where name = 'Strom' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Stromanbieter' from categories where name = 'Strom' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Ökostrom' from categories where name = 'Strom' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Stromrechnung' from categories where name = 'Strom' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Stadtwerke' from categories where name = 'Strom' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Elektrizität' from categories where name = 'Strom' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Stromvertrag' from categories where name = 'Strom' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'E.ON' from categories where name = 'Strom' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Vattenfall' from categories where name = 'Strom' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'EnBW' from categories where name = 'Strom' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'LichtBlick' from categories where name = 'Strom' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Heizung' from categories where name = 'Gas' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Erdgas' from categories where name = 'Gas' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Gasrechnung' from categories where name = 'Gas' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Fernwärme' from categories where name = 'Gas' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Gasvertrag' from categories where name = 'Gas' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Heizkosten' from categories where name = 'Gas' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Ikea' from categories where name = 'Möbel und Haushaltsgeräte' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Möbelhaus' from categories where name = 'Möbel und Haushaltsgeräte' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Möbel' from categories where name = 'Möbel und Haushaltsgeräte' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Waschmaschine' from categories where name = 'Möbel und Haushaltsgeräte' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Kühlschrank' from categories where name = 'Möbel und Haushaltsgeräte' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Elektrogeräte' from categories where name = 'Möbel und Haushaltsgeräte' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Einrichtung' from categories where name = 'Möbel und Haushaltsgeräte' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Trockner' from categories where name = 'Möbel und Haushaltsgeräte' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Spülmaschine' from categories where name = 'Möbel und Haushaltsgeräte' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Poco' from categories where name = 'Möbel und Haushaltsgeräte' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Roller' from categories where name = 'Möbel und Haushaltsgeräte' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Reinigung' from categories where name = 'Haushaltsdienstleistungen' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Putzhilfe' from categories where name = 'Haushaltsdienstleistungen' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Handwerker' from categories where name = 'Haushaltsdienstleistungen' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Hausmeister' from categories where name = 'Haushaltsdienstleistungen' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Reparatur' from categories where name = 'Haushaltsdienstleistungen' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Reinigungskraft' from categories where name = 'Haushaltsdienstleistungen' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Fensterputzer' from categories where name = 'Haushaltsdienstleistungen' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Baufinanzierung' from categories where name = 'Immobilienkredit' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Hypothek' from categories where name = 'Immobilienkredit' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Immobiliendarlehen' from categories where name = 'Immobilienkredit' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Baukredit' from categories where name = 'Immobilienkredit' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Annuitätendarlehen' from categories where name = 'Immobilienkredit' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Kaltmiete' from categories where name = 'Miete / Wohngeld' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Warmmiete' from categories where name = 'Miete / Wohngeld' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Vermieter' from categories where name = 'Miete / Wohngeld' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Miete' from categories where name = 'Miete / Wohngeld' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Wohngeld' from categories where name = 'Miete / Wohngeld' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Mietvertrag' from categories where name = 'Miete / Wohngeld' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Kita' from categories where name = 'Kinderbetreuung und -gruppen' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Kindergarten' from categories where name = 'Kinderbetreuung und -gruppen' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Tagesmutter' from categories where name = 'Kinderbetreuung und -gruppen' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Hort' from categories where name = 'Kinderbetreuung und -gruppen' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Krippe' from categories where name = 'Kinderbetreuung und -gruppen' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Babysitter' from categories where name = 'Kinderbetreuung und -gruppen' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Kinderkrippe' from categories where name = 'Kinderbetreuung und -gruppen' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Betreuung' from categories where name = 'Kinderbetreuung und -gruppen' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Kindesunterhalt' from categories where name = 'Taschengeld / Unterhalt' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Taschengeld' from categories where name = 'Taschengeld / Unterhalt' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Unterhaltszahlung' from categories where name = 'Taschengeld / Unterhalt' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Spielzeug' from categories where name = 'Spielwaren' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Lego' from categories where name = 'Spielwaren' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Toys' from categories where name = 'Spielwaren' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Spielsachen' from categories where name = 'Spielwaren' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Playmobil' from categories where name = 'Spielwaren' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'dm' from categories where name = 'Drogerie' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Rossmann' from categories where name = 'Drogerie' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Müller' from categories where name = 'Drogerie' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Kosmetik' from categories where name = 'Drogerie' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Hygieneartikel' from categories where name = 'Drogerie' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Drogeriemarkt' from categories where name = 'Drogerie' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Shampoo' from categories where name = 'Drogerie' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Pflegeprodukte' from categories where name = 'Drogerie' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Essen' from categories where name = 'Lebensmittel und Getränke' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Supermarkt' from categories where name = 'Lebensmittel und Getränke' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Einkauf' from categories where name = 'Lebensmittel und Getränke' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Rewe' from categories where name = 'Lebensmittel und Getränke' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Edeka' from categories where name = 'Lebensmittel und Getränke' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Lidl' from categories where name = 'Lebensmittel und Getränke' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Aldi' from categories where name = 'Lebensmittel und Getränke' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Kaufland' from categories where name = 'Lebensmittel und Getränke' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Netto' from categories where name = 'Lebensmittel und Getränke' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Penny' from categories where name = 'Lebensmittel und Getränke' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Getränkemarkt' from categories where name = 'Lebensmittel und Getränke' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Bäcker' from categories where name = 'Lebensmittel und Getränke' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Bäckerei' from categories where name = 'Lebensmittel und Getränke' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Metzger' from categories where name = 'Lebensmittel und Getränke' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Lebensmittel' from categories where name = 'Lebensmittel und Getränke' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Wocheneinkauf' from categories where name = 'Lebensmittel und Getränke' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Bio-Markt' from categories where name = 'Lebensmittel und Getränke' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Denns' from categories where name = 'Lebensmittel und Getränke' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Alnatura' from categories where name = 'Lebensmittel und Getränke' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Putzmittel' from categories where name = 'Haushaltsbedarf' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Reinigungsmittel' from categories where name = 'Haushaltsbedarf' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Haushaltswaren' from categories where name = 'Haushaltsbedarf' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Küchenrolle' from categories where name = 'Haushaltsbedarf' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Toilettenpapier' from categories where name = 'Haushaltsbedarf' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'DSL' from categories where name = 'Festnetz und Internet' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Glasfaser' from categories where name = 'Festnetz und Internet' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Router' from categories where name = 'Festnetz und Internet' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Telekom' from categories where name = 'Festnetz und Internet' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Vodafone Kabel' from categories where name = 'Festnetz und Internet' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Internetanschluss' from categories where name = 'Festnetz und Internet' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'WLAN' from categories where name = 'Festnetz und Internet' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, '1&1' from categories where name = 'Festnetz und Internet' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'o2 DSL' from categories where name = 'Festnetz und Internet' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Mobilfunk' from categories where name = 'Handy' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Telefon' from categories where name = 'Handy' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Smartphone-Vertrag' from categories where name = 'Handy' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Prepaid' from categories where name = 'Handy' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'o2' from categories where name = 'Handy' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Vodafone' from categories where name = 'Handy' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Telekom Mobilfunk' from categories where name = 'Handy' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Handyvertrag' from categories where name = 'Handy' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Congstar' from categories where name = 'Handy' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Tierfutter' from categories where name = 'Haustier (-bedarf)' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Tierarztbedarf' from categories where name = 'Haustier (-bedarf)' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Fressnapf' from categories where name = 'Haustier (-bedarf)' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Hund' from categories where name = 'Haustier (-bedarf)' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Katze' from categories where name = 'Haustier (-bedarf)' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Tierbedarf' from categories where name = 'Haustier (-bedarf)' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Zooplus' from categories where name = 'Haustier (-bedarf)' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Arzt' from categories where name = 'Arztbesuch / Krankenhaus' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Klinik' from categories where name = 'Arztbesuch / Krankenhaus' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Krankenhaus' from categories where name = 'Arztbesuch / Krankenhaus' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Facharzt' from categories where name = 'Arztbesuch / Krankenhaus' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Zahnarzt' from categories where name = 'Arztbesuch / Krankenhaus' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Untersuchung' from categories where name = 'Arztbesuch / Krankenhaus' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Hausarzt' from categories where name = 'Arztbesuch / Krankenhaus' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Praxisgebühr' from categories where name = 'Arztbesuch / Krankenhaus' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Physiotherapie' from categories where name = 'Arztbesuch / Krankenhaus' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Apotheke' from categories where name = 'Arznei- und Heilmittel' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Medikamente' from categories where name = 'Arznei- und Heilmittel' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Rezept' from categories where name = 'Arznei- und Heilmittel' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Arznei' from categories where name = 'Arznei- und Heilmittel' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Schmerzmittel' from categories where name = 'Arznei- und Heilmittel' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Friseur' from categories where name = 'Wellness und Beauty' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Kosmetikstudio' from categories where name = 'Wellness und Beauty' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Massage' from categories where name = 'Wellness und Beauty' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Spa' from categories where name = 'Wellness und Beauty' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Nagelstudio' from categories where name = 'Wellness und Beauty' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Beauty' from categories where name = 'Wellness und Beauty' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Kosmetikerin' from categories where name = 'Wellness und Beauty' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Kindergeld' from categories where name = 'Staatliche Leistung und Förderung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Elterngeld' from categories where name = 'Staatliche Leistung und Förderung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'BAföG' from categories where name = 'Staatliche Leistung und Förderung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Wohngeld-Zuschuss' from categories where name = 'Staatliche Leistung und Förderung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Arbeitslosengeld' from categories where name = 'Staatliche Leistung und Förderung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Bürgergeld' from categories where name = 'Staatliche Leistung und Förderung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Zuschuss' from categories where name = 'Staatliche Leistung und Förderung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Alimente' from categories where name = 'Unterhalt' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Unterhaltszahlung erhalten' from categories where name = 'Unterhalt' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Dividende' from categories where name = 'Kapitaleinkommen' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Zinsen' from categories where name = 'Kapitaleinkommen' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Ausschüttung' from categories where name = 'Kapitaleinkommen' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Kapitalertrag' from categories where name = 'Kapitaleinkommen' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Zinserträge' from categories where name = 'Kapitaleinkommen' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Einzahlung' from categories where name = 'Bareinzahlung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Bargeld einzahlen' from categories where name = 'Bareinzahlung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Bareinzahlung Automat' from categories where name = 'Bareinzahlung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Miete erhalten' from categories where name = 'Mieteinnahmen' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Vermietung' from categories where name = 'Mieteinnahmen' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Mietertrag' from categories where name = 'Mieteinnahmen' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Rente' from categories where name = 'Rente und Pension' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Pension' from categories where name = 'Rente und Pension' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Altersvorsorge-Auszahlung' from categories where name = 'Rente und Pension' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Rentenzahlung' from categories where name = 'Rente und Pension' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Lohn' from categories where name = 'Gehalt' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Einkommen' from categories where name = 'Gehalt' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Gehaltseingang' from categories where name = 'Gehalt' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Arbeitgeber' from categories where name = 'Gehalt' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Gehaltszahlung' from categories where name = 'Gehalt' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Lohnzahlung' from categories where name = 'Gehalt' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Unfallschutz' from categories where name = 'Unfallversicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Unfallpolice' from categories where name = 'Unfallversicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Krankenkasse' from categories where name = 'Krankenversicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'GKV' from categories where name = 'Krankenversicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'PKV' from categories where name = 'Krankenversicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'TK' from categories where name = 'Krankenversicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'AOK' from categories where name = 'Krankenversicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Barmer' from categories where name = 'Krankenversicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'DAK' from categories where name = 'Krankenversicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'IKK' from categories where name = 'Krankenversicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'KKH' from categories where name = 'Krankenversicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Gebäudeversicherung' from categories where name = 'Wohngebäudeversicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Hausversicherung' from categories where name = 'Wohngebäudeversicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Hausrat' from categories where name = 'Hausratversicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Rechtsschutz' from categories where name = 'Rechtsschutzversicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Haftpflicht' from categories where name = 'Haftpflichtversicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Privathaftpflicht' from categories where name = 'Haftpflichtversicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Pflegekasse' from categories where name = 'Pflegeversicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'BU-Versicherung' from categories where name = 'Berufsunfähigkeitsversicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Berufsunfähigkeit' from categories where name = 'Berufsunfähigkeitsversicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'BU' from categories where name = 'Berufsunfähigkeitsversicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Tierkrankenversicherung' from categories where name = 'Tierversicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Hundeversicherung' from categories where name = 'Tierversicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Tier-OP-Versicherung' from categories where name = 'Tierversicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Zahnzusatz' from categories where name = 'Kranken-Zusatzversicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Auslandskrankenversicherung' from categories where name = 'Kranken-Zusatzversicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Zusatzversicherung' from categories where name = 'Kranken-Zusatzversicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Lebensversicherung' from categories where name = 'Risiko-Lebensversicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Risikolebensversicherung' from categories where name = 'Risiko-Lebensversicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Reiserücktrittsversicherung' from categories where name = 'Reiseversicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Auslandsreiseversicherung' from categories where name = 'Reiseversicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Kirchensteuer' from categories where name = 'Kirche / Spende' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Spende' from categories where name = 'Kirche / Spende' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Kollekte' from categories where name = 'Kirche / Spende' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Spendenaktion' from categories where name = 'Kirche / Spende' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Kino' from categories where name = 'Freizeitaktivitäten' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Konzert' from categories where name = 'Freizeitaktivitäten' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Freizeitpark' from categories where name = 'Freizeitaktivitäten' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Hobby' from categories where name = 'Freizeitaktivitäten' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Verein' from categories where name = 'Freizeitaktivitäten' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Mitgliedsbeitrag' from categories where name = 'Freizeitaktivitäten' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Museum' from categories where name = 'Freizeitaktivitäten' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Zoo' from categories where name = 'Freizeitaktivitäten' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Essen gehen' from categories where name = 'Restaurant / Cafe / Bar' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Gastronomie' from categories where name = 'Restaurant / Cafe / Bar' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Kneipe' from categories where name = 'Restaurant / Cafe / Bar' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Imbiss' from categories where name = 'Restaurant / Cafe / Bar' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Lieferdienst' from categories where name = 'Restaurant / Cafe / Bar' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Take-away' from categories where name = 'Restaurant / Cafe / Bar' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Restaurant' from categories where name = 'Restaurant / Cafe / Bar' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Café' from categories where name = 'Restaurant / Cafe / Bar' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Bar' from categories where name = 'Restaurant / Cafe / Bar' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Lieferando' from categories where name = 'Restaurant / Cafe / Bar' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Pizza' from categories where name = 'Restaurant / Cafe / Bar' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Döner' from categories where name = 'Restaurant / Cafe / Bar' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Fitnessstudio' from categories where name = 'Sport und Fitness' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Gym' from categories where name = 'Sport und Fitness' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Sportverein' from categories where name = 'Sport und Fitness' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'McFit' from categories where name = 'Sport und Fitness' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Yoga' from categories where name = 'Sport und Fitness' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Fitness First' from categories where name = 'Sport und Fitness' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Crossfit' from categories where name = 'Sport und Fitness' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Autoversicherung' from categories where name = 'KFZ-Versicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Kfz-Haftpflicht' from categories where name = 'KFZ-Versicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Kaskoversicherung' from categories where name = 'KFZ-Versicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Autokredit' from categories where name = 'KFZ-Kredit / Leasingrate / KFZ-Kauf' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Leasing' from categories where name = 'KFZ-Kredit / Leasingrate / KFZ-Kauf' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Autokauf' from categories where name = 'KFZ-Kredit / Leasingrate / KFZ-Kauf' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Leasingrate' from categories where name = 'KFZ-Kredit / Leasingrate / KFZ-Kauf' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Autofinanzierung' from categories where name = 'KFZ-Kredit / Leasingrate / KFZ-Kauf' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Werkstatt' from categories where name = 'KFZ-Sonstige' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Reifen' from categories where name = 'KFZ-Sonstige' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'TÜV' from categories where name = 'KFZ-Sonstige' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Autopflege' from categories where name = 'KFZ-Sonstige' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Reparatur Auto' from categories where name = 'KFZ-Sonstige' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Autowäsche' from categories where name = 'KFZ-Sonstige' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Benzin' from categories where name = 'Tanken' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Diesel' from categories where name = 'Tanken' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Kraftstoff' from categories where name = 'Tanken' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Tankstelle' from categories where name = 'Tanken' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Aral' from categories where name = 'Tanken' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Shell' from categories where name = 'Tanken' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Esso' from categories where name = 'Tanken' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Bahn' from categories where name = 'Taxi / ÖPNV / Car- und Bikesharing' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Bus' from categories where name = 'Taxi / ÖPNV / Car- und Bikesharing' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Nahverkehr' from categories where name = 'Taxi / ÖPNV / Car- und Bikesharing' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Uber' from categories where name = 'Taxi / ÖPNV / Car- und Bikesharing' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Deutschlandticket' from categories where name = 'Taxi / ÖPNV / Car- und Bikesharing' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Fahrschein' from categories where name = 'Taxi / ÖPNV / Car- und Bikesharing' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'DB' from categories where name = 'Taxi / ÖPNV / Car- und Bikesharing' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'MVV' from categories where name = 'Taxi / ÖPNV / Car- und Bikesharing' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'BVG' from categories where name = 'Taxi / ÖPNV / Car- und Bikesharing' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Fahrkarte' from categories where name = 'Taxi / ÖPNV / Car- und Bikesharing' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Sparbuch' from categories where name = 'Festgeld / Tagesgeld / Sparkonto' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Tagesgeldkonto' from categories where name = 'Festgeld / Tagesgeld / Sparkonto' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Festgeldkonto' from categories where name = 'Festgeld / Tagesgeld / Sparkonto' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Bausparvertrag' from categories where name = 'Bausparen' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Bausparkasse' from categories where name = 'Bausparen' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Schwäbisch Hall' from categories where name = 'Bausparen' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Wüstenrot' from categories where name = 'Bausparen' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Lebensversicherung Sparanteil' from categories where name = 'Kapitallebensversicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Rürup' from categories where name = 'Private Rentenversicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Riester' from categories where name = 'Private Rentenversicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Rentenversicherung' from categories where name = 'Private Rentenversicherung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'ETF' from categories where name = 'Wertpapieranlage' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Aktien' from categories where name = 'Wertpapieranlage' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Depot' from categories where name = 'Wertpapieranlage' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Fonds' from categories where name = 'Wertpapieranlage' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Sparplan' from categories where name = 'Wertpapieranlage' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Trade Republic' from categories where name = 'Wertpapieranlage' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Scalable Capital' from categories where name = 'Wertpapieranlage' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Wertpapiersparplan' from categories where name = 'Wertpapieranlage' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Gold' from categories where name = 'Wertgegenstände und andere Anlagen' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Krypto' from categories where name = 'Wertgegenstände und andere Anlagen' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Bitcoin' from categories where name = 'Wertgegenstände und andere Anlagen' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Sammlerstücke' from categories where name = 'Wertgegenstände und andere Anlagen' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Edelmetalle' from categories where name = 'Wertgegenstände und andere Anlagen' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Buchhandlung' from categories where name = 'Bücher / Zeitungen / Zeitschriften' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Abo' from categories where name = 'Bücher / Zeitungen / Zeitschriften' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Zeitung' from categories where name = 'Bücher / Zeitungen / Zeitschriften' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Zeitschrift' from categories where name = 'Bücher / Zeitungen / Zeitschriften' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Amazon Buch' from categories where name = 'Bücher / Zeitungen / Zeitschriften' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Thalia' from categories where name = 'Bücher / Zeitungen / Zeitschriften' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Zeitungsabo' from categories where name = 'Bücher / Zeitungen / Zeitschriften' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Kleidung' from categories where name = 'Bekleidung / Schuhe / Accessoires' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Schuhe' from categories where name = 'Bekleidung / Schuhe / Accessoires' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Mode' from categories where name = 'Bekleidung / Schuhe / Accessoires' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Zalando' from categories where name = 'Bekleidung / Schuhe / Accessoires' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'H&M' from categories where name = 'Bekleidung / Schuhe / Accessoires' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'C&A' from categories where name = 'Bekleidung / Schuhe / Accessoires' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'About You' from categories where name = 'Bekleidung / Schuhe / Accessoires' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Klamotten' from categories where name = 'Bekleidung / Schuhe / Accessoires' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Elektronik' from categories where name = 'Unterhaltungselektronik und Software' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'App-Store' from categories where name = 'Unterhaltungselektronik und Software' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Software' from categories where name = 'Unterhaltungselektronik und Software' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Saturn' from categories where name = 'Unterhaltungselektronik und Software' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'MediaMarkt' from categories where name = 'Unterhaltungselektronik und Software' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Handy kaufen' from categories where name = 'Unterhaltungselektronik und Software' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Laptop' from categories where name = 'Unterhaltungselektronik und Software' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Bürobedarf' from categories where name = 'Büromaterial' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Drucker' from categories where name = 'Büromaterial' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Papier' from categories where name = 'Büromaterial' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Stifte' from categories where name = 'Büromaterial' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Ordner' from categories where name = 'Büromaterial' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Streaming' from categories where name = 'TV / Video / Musik' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Netflix' from categories where name = 'TV / Video / Musik' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Spotify' from categories where name = 'TV / Video / Musik' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Amazon Prime' from categories where name = 'TV / Video / Musik' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Disney+' from categories where name = 'TV / Video / Musik' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Apple Music' from categories where name = 'TV / Video / Musik' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'YouTube Premium' from categories where name = 'TV / Video / Musik' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Booking.com' from categories where name = 'Hotel und Unterkunft' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Airbnb' from categories where name = 'Hotel und Unterkunft' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Ferienwohnung' from categories where name = 'Hotel und Unterkunft' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Hotel' from categories where name = 'Hotel und Unterkunft' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Hostel' from categories where name = 'Hotel und Unterkunft' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Reisebüro' from categories where name = 'Pauschalreise' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Urlaubsreise' from categories where name = 'Pauschalreise' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'TUI' from categories where name = 'Pauschalreise' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Pauschalurlaub' from categories where name = 'Pauschalreise' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Flug' from categories where name = 'Transport' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Flugticket' from categories where name = 'Transport' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Bahnfahrt' from categories where name = 'Transport' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Mietwagen' from categories where name = 'Transport' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Lufthansa' from categories where name = 'Transport' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Ryanair' from categories where name = 'Transport' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Flixbus' from categories where name = 'Transport' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Umbuchung' from categories where name = 'Kontentransfer' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Eigenüberweisung' from categories where name = 'Kontentransfer' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Transfer' from categories where name = 'Kontentransfer' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Kontoübertrag' from categories where name = 'Kontentransfer' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Kontoführungsgebühr' from categories where name = 'Bankgebühren' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Kartengebühr' from categories where name = 'Bankgebühren' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Depotgebühr' from categories where name = 'Bankgebühren' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Geldautomat' from categories where name = 'Barauszahlung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Abhebung' from categories where name = 'Barauszahlung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Bargeldabhebung' from categories where name = 'Barauszahlung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'ATM' from categories where name = 'Barauszahlung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Kreditkartenrechnung' from categories where name = 'Kreditkartenabrechnung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Kartenabrechnung' from categories where name = 'Kreditkartenabrechnung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Visa-Abrechnung' from categories where name = 'Kreditkartenabrechnung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Mastercard-Abrechnung' from categories where name = 'Kreditkartenabrechnung' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Kreditrate' from categories where name = 'Kredittilgung und -zinsen' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Ratenkredit' from categories where name = 'Kredittilgung und -zinsen' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Darlehen' from categories where name = 'Kredittilgung und -zinsen' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Tilgung' from categories where name = 'Kredittilgung und -zinsen' and is_deleted = 0;
insert or ignore into category_aliases (category_id, alias) select id, 'Kreditzinsen' from categories where name = 'Kredittilgung und -zinsen' and is_deleted = 0;
